#!/bin/bash

HelloWorld2.exe: HelloWorld2.h HelloWorld2.cpp
	g++ -g -o HelloWorld2.exe HelloWorld2.h HelloWorld2.cpp

run:
	./HelloWorld2.exe

debug:
	gdb ./HelloWorld2.exe

clean:
	rm ./HelloWorld2.exe
