#!/bin/bash

HelloWorld3.exe: HelloWorld3.h HelloWorld3.cpp
	g++ -g -o HelloWorld3.exe HelloWorld3.h HelloWorld3.cpp

run:
	./HelloWorld3.exe
    
debug:
	gdb ./HelloWorld3.exe
    
clean:
	rm ./HelloWorld3.exe
